name: Compile (MacOS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --features "sqlite,ora"
    - name: Run tests
      run: cargo test --verbose
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: debug-binary
        path: target/debug/dbc